# RHEL 9.5 Golden Image Baseline
# Disable unused filesystems

sudo vi /etc/modprobe.d/disable-filesystems.conf


install cramfs /bin/false
install freevxfs /bin/false
install jffs2 /bin/false
install hfs /bin/false
install hfsplus /bin/false
install squashfs /bin/false
install udf /bin/false


blacklist cramfs
blacklist freevxfs
blacklist jffs2
blacklist hfs
blacklisst hfsplus
blacklist squashfs
blacklist udf
