# RHEL 9.5 Golden Image Baseline
# Time Synchronization Configuration

### Step By Step

1. dnf -y install chrony
2. systemctl enable --now chronyd
3. sudo vi /etc/chony.conf
### Add the following:

  pool time.google.com iburst

### Also ensure the following directives are in the file. (they should be there by default)

driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
